name: PROJECT - FreshFood

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Docker provider'
        required: true
        default: 'docker'
        type: choice
        options:
          - docker
      registry:
        description: 'Docker provider'
        required: true
        default: 'dangkhoi141'
      service:
        description: 'Service name'
        required: true
        default: 'fresh-food'

env:
  CONFIGURATION: 'DEV'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get tag name
        id: get_tag
        run: |
          VERSION="${{ github.run_id }}"
          DOCKER_TAGS="${{ inputs.registry }}/${{ inputs.service }}:${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: ${{ inputs.provider == 'docker' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.docker_tags }}
          build-args: |
            SWAGGER_VERSION=${{ env.version }}

  deploy:
    name: Deploy Dev
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          VERSION="${{ github.run_id }}"
          DOCKER_TAGS="${{ inputs.registry }}/${{ inputs.service }}:${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV
          echo "docker_tags=${DOCKER_TAGS}" >> $GITHUB_ENV
